apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vu270uaec-go 
  janus-idp.io/tekton: vu270uaec-go
  backstage.io/kubernetes-id: vu270uaec-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vu270uaec-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml