apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vu270uaec-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vu270uaec-go 
  name: vu270uaec-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vu270uaec-go 
